
### Teste sort com vetor válido
POST http://localhost:3000/sort HTTP/1.1
content-type: application/json

{
  "vector": [3, 6, 1, 8, 5, 9, 5, 1, 0, -1, 8]
}

### Test sort com vetor com menos de 2 elementos
POST http://localhost:3000/sort HTTP/1.1
content-type: application/json

{
  "vector": [3]
}

### Teste sort com vetor com mais de 20 elementos
POST http://localhost:3000/sort HTTP/1.1
content-type: application/json

{
  "vector": [3, 6, 1, 8, 5, 9, 5, 1, 0, -1, 8, 3, 6, 1, 8, 5, 9, 5, 1, 0, -1, 8]
}

### Teste minmax com vetor válido
POST http://localhost:3000/minmax HTTP/1.1
content-type: application/json

{    
    "vector": [3, 6, 1, 8, 5, 9, 5, 1, 0, -1, 8]
}

### Teste minmax com vetor com menos de 2 elementos
POST http://localhost:3000/minmax HTTP/1.1
content-type: application/json

{    
    "vector": [3]
}

### Teste minmax com vetor com mais de 20 elementos
POST http://localhost:3000/minmax HTTP/1.1
content-type: application/json

{    
    "vector": [3, 6, 1, 8, 5, 9, 5, 1, 0, -1, 8, 3, 6, 1, 8, 5, 9, 5, 1, 0, -1, 8]
}